version: "3"

services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=budgetdb
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        volumes:
            - postgres:/data/postgres/db
        ports:
            - "5432:5432"

volumes:
    postgres:
